Bug 1985779 - Hide -Wformat-overflow warning with GCC 10. r=gfx-reviewers,lsalzman
GCC 10 warns that:
dom/canvas/ClientWebGLContext.h:891:22: error: '%s' directive argument is null [-Werror=format-overflow=]

(which is turned into an error by --enable-warnings-as-errors)

Technically, it's not wrong, because FuncName() can return null, and
MOZ_ASSERT only does something on debug builds, so the compiler doesn't
know that it can't be null in practice.

Differential Revision: https://phabricator.services.mozilla.com/D263880