Bug 2012831 [wpt PR 57365] - Throw TypeError for incompatible types in CSSNumericValue operations, a=testonly
Automatic update from web-platform-tests
Throw TypeError for incompatible types in CSSNumericValue operations

This patch modifies min(), max(), mul(), and div() to throw a TypeError
when types are incompatible. Previously, Chromium returned null in these
cases because it used a constructor that did not throw errors. This
patch changes the constructors to properly handle these errors, aligning
Blink's behavior with the CSS Typed OM specification.

[1]: https://drafts.css-houdini.org/css-typed-om-1/#dom-cssnumericvalue-min
[2]: https://drafts.css-houdini.org/css-typed-om-1/#dom-cssnumericvalue-max
[3]: https://drafts.css-houdini.org/css-typed-om-1/#dom-cssnumericvalue-mul
[4]: https://drafts.css-houdini.org/css-typed-om-1/#dom-cssnumericvalue-div

Bug: 477036003
Change-Id: I182a7917e30e6361b3d117bad4c99a7622e2252b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7493838
Commit-Queue: Jinho Bang <zino@chromium.org>
Reviewed-by: Rune Lillesveen <futhark@chromium.org>
Reviewed-by: Jinho Bang <zino@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1575569}

--

wpt-commits: 3e32b1b196d97a9ac8f373707a1825f031c156de
wpt-pr: 57365